Солтисюк Дмитро, студент ТУ-12-21-ІПЗ

= Лабораторна робота №2

*Тема:* Скрипт для генерації бази даних постачальників.

*Мета:* Згенерувати базу даних постачальників з урахуванням основних принципів створення та налагодження скриптів з декількох операторів.

== Виконання

[start={list-counter}]
{counter:list-counter}. Створення бази даних та таблиць:

[source,sql]
----
CREATE DATABASE IF NOT EXISTS suppliers_db;
USE suppliers_db;

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INT AUTO_INCREMENT PRIMARY KEY,
    supplier_name VARCHAR(255),
    address VARCHAR(255),
    contact_person VARCHAR(255)
);
----

В цьому блоку коду створюється база даних `suppliers_db` та таблиця `suppliers`, яка містить інформацію про постачальників. Кожен постачальник має унікальний ідентифікатор `supplier_id`, назву компанії, адресу та контактну особу.

{counter:list-counter}. Створення таблиці продуктів:

[source,sql]
----
CREATE TABLE IF NOT EXISTS products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(255),
    price DECIMAL(10,2),
    supplier_id INT,
    FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);
----

У цьому блоку коду створюється таблиця `products`, яка містить інформацію про продукти. Кожен продукт має унікальний ідентифікатор `product_id`, назву продукту, ціну та зв'язок з постачальником через поле `supplier_id`, яке є зовнішнім ключем, посилаючимся на поле `supplier_id` в таблиці `suppliers`.

{counter:list-counter}. Вставка декількох записів в таблиці постачальників та продуктів:

[source,sql]
----
INSERT INTO suppliers (supplier_name, address, contact_person) VALUES
('Supplier A', '123 Main Street', 'John Doe'),
('Supplier B', '456 Oak Avenue', 'Jane Smith');

INSERT INTO products (product_name, price, supplier_id) VALUES
('Product X', 49.99, 1),
('Product Y', 29.99, 2);
----

У цьому блоку коду виконується вставка декількох записів у таблиці `suppliers` та `products`. Ці дані створюють декілька постачальників та продуктів із зазначенням їхніх характеристик.

{counter:list-counter}. Виконання оператора вибірки для перевірки даних:

[source,sql]
----
SELECT * FROM suppliers;
SELECT * FROM products;
----

Опис: У цьому блоку коду виконується запит на вибірку всіх записів з таблиць `suppliers` та `products`, щоб перевірити, чи були дані вставлені коректно.

== Висновок

У результаті виконання лабораторної роботи було успішно створено базу даних "suppliers_db" для зберігання інформації про постачальників та їхні продукти. Таблиця "suppliers" містить дані про постачальників, включаючи їхні назви, адреси та контактні особи. Таблиця "products" зберігає інформацію про продукти, включаючи їхні назви, ціни та посилання на відповідного постачальника. Декілька записів було вставлено в кожну таблицю, а також було виконано запити для перевірки даних. Усі етапи виконані вірно та без помилок.
