Солтисюк Дмитро, студент ТУ-12-21-ІПЗ.

= Звіт за практичну роботу №2. Перетворення кольорів.

У даному звіті будуть представлені результати виконання практичної роботи №2 з теми "Перетворення кольорів". Під час цієї роботи ми працювали з кольорами у форматах HEX, RGB, HSL, CMYK, HSB та виконували їх взаємне перетворення.

== Результати

[cols="6",options="header"]
|===
| Заданий колір | HEX | RGB | HSL | CMYK | HSB
| #94519e | #94519e | RGB(148, 81, 158) | HSL(292°, 32%, 47%) | CMYK(6%, 49%, 0%, 38%) | HSB(292°, 49%, 62%)
| #c9ffe1 | #c9ffe1 | RGB(201, 255, 225) | HSL(149°, 100%, 89%) | CMYK(21%, 0%, 12%, 0%) | HSB(149°, 21%, 100%)
| #94519e | #94519e | RGB(148, 81, 158) | HSL(292°, 32%, 47%) | CMYK(6%, 49%, 0%, 38%) | HSB(292°, 49%, 62%)
| hsl(147, 100%, 89%) | #dfffff | RGB(223, 255, 223) | HSL(147°, 100%, 89%) | CMYK(13%, 0%, 13%, 0%) | HSB(147°, 13%, 100%)
| CMYK(0%, 100%, 100%, 1%) | #ff0000 | RGB(255, 0, 0) | - | CMYK(0%, 100%, 100%, 1%) | HSB(0°, 100%, 100%)
|===

=== Висновок

Під час виконання практичної роботи були успішно перетворені кольори між форматами HEX, RGB, HSL, CMYK та HSB. Використання цих різних форматів дозволяє ефективно працювати з кольорами та виконувати їх конвертацію в різноманітні формати для потреб різних програм та проектів.
