Солтисюк Дмитро, студент ТУ-12-21-ІПЗ

= Лабораторна робота №4: SQLite - вбудована БД

Тема:: SQLite - вбудована БД.

Мета:: Розробити програму на мові C#, що задовольняє вимоги лабораторної роботи 3, за винятком виконання операції вибірки. Додаток створює БД і виконує кілька операторів вставки для початкового наповнення. Операції вибірки виконувати.


== Виконання

Програма реалізує вимоги лабораторної роботи, використовуючи мову програмування C# та вбудовану базу даних SQLite. Під час виконання програма здійснює підключення до бази даних SQLite, створює таблицю Suppliers з використанням AUTOINCREMENT для поля SupplierID, обмеження NOT NULL для поля SupplierName та за замовчуванням встановлює значення 'Unknown' для поля Address. Далі програма вставляє кілька записів в таблицю, демонструючи працездатність обмежень цілісності даних.

[source,csharp]
----
include::Main.cs[]
----


== Висновок

У цій лабораторній роботі ми розробили програму на мові C#, яка створює базу даних SQLite та виконує кілька операторів вставки для початкового наповнення таблиці. Програма задовольняє вимоги лабораторної роботи 3, демонструючи працездатність AUTOINCREMENT, NOT NULL і DEFAULT XXX.
